### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by evhan55** [jeromeetienne/AR.js#124]
Hi!

I love AR.js!
I recently tried one of my projects at https://8-blocks.glitch.me and it wasn't working (got an error), but then I updated to linking to A-Frame 0.6.0 and it works again.

However, it's much slower than I remember, the graphics appear very sluggishly now, as compared to with A-Frame 0.5.0.

Just wanted to report, thank you!
Evelyn

**Comment by jeromeetienne** [comment]
anybody can confirm that aframe 0.6 is significantly slower than aframe 0.5

**Comment by jeromeetienne** [comment]
hi, i found the issue :( 

it was a silly mistake of mine which made everybody run on the slow profile.. i forgot to rename some properties. sorry about that - [link](https://github.com/jeromeetienne/AR.js/commit/6fa0e41ddf5c3da4c293199f03d4270c30a9e9e6#diff-67fb00d7946808ae788cb08be9446755)

it is fixed now and i added some sanity check to avoid that in the future.

**Comment by evhan55** [comment]
Hi!  Oh great, thank you for the update!  I will test again sometime soon and post again if I still see an issue.

Glad you found the issue, and that it was a simple one!
